Updates to template

diff --git a/template/single/use_template b/template/single/use_template
--- a/template/single/use_template
+++ b/template/single/use_template
@@ -2,20 +2,24 @@
 {{.Copyright}}
 # Generated by dbdeployer {{.AppVersion}} using {{.TemplateName}} on {{.DateTime}}
 source {{.SandboxDir}}/sb_include
+
+export MYSQL_EDITOR=`which mysql`
+
 [ -n "$TEST_REPL_DELAY" -a -f $SBDIR/data/mysql-relay.index ] && sleep $TEST_REPL_DELAY
 [ -z "$MYSQL_EDITOR" ] && MYSQL_EDITOR="$BASEDIR/bin/mysql"
 if [ ! -x $MYSQL_EDITOR ]
 then
 	if [ -x $SBDIR/$MYSQL_EDITOR ]
 	then
-MYSQL_EDITOR=$SBDIR/$MYSQL_EDITOR
+		MYSQL_EDITOR=$SBDIR/$MYSQL_EDITOR
 	else
-echo "MYSQL_EDITOR '$MYSQL_EDITOR' not found or not executable"
-exit 1
+		echo "MYSQL_EDITOR '$MYSQL_EDITOR' not found or not executable"
+		exit 1
 	fi
 fi
 HISTDIR={{.HistoryDir}}
 [ -z "$HISTDIR" ] && export HISTDIR=$SBDIR
 [ -z "$MYSQL_HISTFILE" ] && export MYSQL_HISTFILE="$HISTDIR/.mysql_history"
 MY_CNF=$SBDIR/my.sandbox.cnf
+
 $MYSQL_EDITOR --defaults-file=$MY_CNF $MYCLIENT_OPTIONS "$@"
